# 테스트 (1)

<br>

## 1. 테스트를 하는 이유
<br>

    - 기능이 많으면 수작업으로 테스트 하기 힘듬
    - 프로그램이 프로그램을 테스트할 수 있도록 자동화함
    - 테스트 환경을 최대한 실제 환경과 비슷하게 해야함
    - 아무리 철저하게 테스트해도 에러를 완전히 막을 수는 없음
    - 한 번 발생한 에러는 테스트로 만들어두면 같은 에러가 발생하지 않게 막을 수 있음(회귀 테스트)
    - 코드를 수정할 때 프로그램이 자동으로 어떤 부분이 에러가 나는지 알려줌

<br>

***

<br>

## 2. Jest

<br>

```javascript

// package.json
  "scripts": {
    "test": "jest",
    "start": "nodemon app"
  },

```

<br>

    - npm i -D jest 실행 후 package.json 수정
    - npm test를 실행하면 jest가 알아서 test.js 파일을 찾아서 테스트를 진행

<br>

***

<br>

## 3. 단위테스트(유닛테스트)

<br>

```javascript

// routes/middlewares.test.js
const { isLoggedIn, isNotLoggedIn } = require('./middlewares');

describe('isLoggedIn', () => {
    const res = {
      status: jest.fn(() => res),
      send: jest.fn(),
    };
    const next = jest.fn();
  
    test('로그인 되어있으면 isLoggedIn이 next를 호출해야 함', () => {
      const req = {
        isAuthenticated: jest.fn(() => true),
      };
      isLoggedIn(req, res, next);
      expect(next).toBeCalledTimes(1);
    });
  
    test('로그인 되어있지 않으면 isLoggedIn이 에러를 응답해야 함', () => {
      const req = {
        isAuthenticated: jest.fn(() => false),
      };
      isLoggedIn(req, res, next);
      expect(res.status).toBeCalledWith(403);
      expect(res.send).toBeCalledWith('로그인 필요');
    });
  });
  

```

<br>

    - 단위테스트(유닛테스트): 함수나 메소드에 대한 테스트 케이스를 작성
    - 함수 하나를 describe로 그룹화
    - 함수의 파라미터들을 만들기 애매할 때 jest.fn()를 이용하여 가짜(mock)로 생성
    - expect(next).toBeCalledTimes(n): 몇번 호출 되었는지 검증
    - expect(values).toBeCalledWith(기대되는 값): 인자로 무엇이 넘어왔는지 검증

<br>

***

<br>

## 4. 데이터베이스 모킹(Mocking)

<br>

```javascript

const { addFollowing } = require('./user');
jest.mock('../models/user');
const User = require('../models/user');

describe('addFollowing', () => {
    const req = {
        user: { id: 1 },
        params: { id: 2 },
    };
    const res = {
        status: jest.fn(() => res),
        send: jest.fn(),
    };
    const next = jest.fn();
    test('User를 찾고 팔로잉을 추가하고 success를 응답', async () => {
        User.findOne.mockReturnValue(Promise.resolve({ 
            id: 1, name: 'daldal',
            addFollowings(value) {
                return Promise.resolve(true);
            }
    }));
        await addFollowing(req, res, next);
        expect(res.send).toBeCalledWith('success');
    });

    test('User를 찾지 못했을 때 404 코드와 함께 no user를 응답', async () => {
        User.findOne.mockReturnValue(Promise.resolve(null));
        await addFollowing(req, res, next);
        expect(res.status).toBeCalledWith(404);
        expect(res.send).toBeCalledWith('no user');
    })

    test('DB에서 에러 발생하면 next(error)를 호출', async () => {
        const error = '테스트용 에러';
        User.findOne.mockReturnValue(Promise.reject(error));
        await addFollowing(req, res, next);
        expect(next).toBeCalledWith(error);
    })
});

```

<br>

    - 단위테스트를 할 때 데이터베이스와 관련된 것도 같이 테스트하면 복잡해짐
    - 데이터베이스도 모킹하여 처리
    - 단위테스트에 필요한 Model을 선언하기 전에 jest.mock('/모델 경로명');을 선언
    - 모델에서 값을 읽을 때, mockReturnValue(Promise.resolve({옵션}))을 이용하여 강제로 성공하게 하거나
    - mockReturnValue(Promise.resolve(null))을 이용하여 강제로 실패하게함
    - DB 자체에서 에러나게 하려면 mockReturnValue(Promise.reject(error))를 이용

<br>

***

<br>
